crc/urls.py
"""crc URL Configuration"""

from django.conf.urls import include, url, handler500
from django.contrib import admin 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, logout, password_reset, password_reset_confirm, password_reset_complete, password_reset_done
from django.views.generic import TemplateView

#handler500 = "teledm.views.server_error"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^climdata.u-bourgogne.fr/Catalogues', include('portailCRC.urls', namespace='portailCRC', app_name='portailCRC')),
    url(r'^climdata.u-bourgogne.fr/teledm/', include('teledm.urls', namespace='teledm', app_name='teledm')),
    #url(r'^user/', include('usermanagement.urls')),
    url(r'^accounts/password_reset/$', password_reset, {'template_name': 'registration/password_reset_form.html'}, name='password_reset'),
    url(r'^accounts/password_reset_complete/$', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'}, name='password_reset_complete'),
    url(r'^accounts/password_reset_done/$', password_reset_done, {'template_name': 'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^accounts/password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm, {'template_name': 'registration/password_reset_confirm.html'}, name="password_reset_confirm"),
    url(r'^accounts/login/$', login, {'template_name': 'registration/login.html'}, name="login"),
    url(r'^accounts/logout/$', logout, {'template_name': 'registration/logout.html', 'next_page':'/accounts/login/'}, name="logout"),
    url(r'^accounts/profile/$', login_required(TemplateView.as_view(template_name="registration/profile.html"))),
]

teledm/urls.py
from django.conf.urls import url, handler400, handler403, handler404, handler500
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from . import views




handler500 = 'teledm.views.server_error'


app_name = 'teledm'
urlpatterns = [
    ###pages
    url(r'^$', TemplateView.as_view(template_name='teledm/home.html'), name='home'),#login_required(TemplateView.as_view(template_name='teledm/home.html')), name='home'),
    url(r'^mapViewer/$', views.mapViewer, name='mapViewer'),
    url(r'^mapDist/$', views.mapDist, name='mapDist'),
    url(r'^calval/$', views.calval, name='calval'),
    url(r'^localisation/$', TemplateView.as_view(template_name='teledm/localisation.html'), name='localisation'),
    url(r'^test/$', TemplateView.as_view(template_name='teledm/test.html'), name='test'),
    ###proxy
    url(r'^proxyajax/(?P<path>.*)$', views.proxyAjax, name='mapViewer'),
    url(r'^minmax/(?P<path>.*)$', views.minmax, name='minmax'),
    url(r'^dates/(?P<path>.*)$', views.dates, name='mapViewer'),
    url(r'^proxywms/(?P<path>.*)$', views.proxyWMS, name='mapViewer'),
    url(r'^proxydownload/(?P<path>.*)$', views.proxyDownload, name='mapViewer'),
    url(r'^colorbar/(?P<path>.*)$', views.colorbar, name='colorbar'),
    url(r'^proxyncss/(?P<path>.*)$', views.proxyNCSS, name='mapViewer'),
    ###tuto
    url(r'^DB/$', TemplateView.as_view(template_name='teledm/db.html'), name='DB'),
    url(r'^traitementsData/$', TemplateView.as_view(template_name='teledm/traitementsData.html'), name='traitementsData'),
    url(r'^tutoMap/$', TemplateView.as_view(template_name='teledm/tutoMap.html'), name='tutoMap'),
    url(r'^tutoCalVal/$', TemplateView.as_view(template_name='teledm/tutoCalVal.html'), name='tutoCalVal'),
    url(r'^tutoExtraction/$', TemplateView.as_view(template_name='teledm/tutoExtraction.html'), name='tutoExtraction'),
    url(r'^stationsAeronetTeom/$', TemplateView.as_view(template_name='teledm/stations.html'), name='stations'),
]

teledm/views.py
#-*- coding: utf-8 -*-

from django.shortcuts import HttpResponse, render, redirect
from django.http import Http404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.template import RequestContext
from django.core.serializers.json import DjangoJSONEncoder
from django.conf import settings
from django.utils.datastructures import MultiValueDictKeyError
from sendfile import sendfile
import json, simplejson
import requests
from StringIO import StringIO
import os
import pandas as pd
import numpy as np
from datetime import datetime
from moy_dist_parallel import calc_moy
from traitement import traitementDF
from pathFiles import PathFile
from scatterPlots import scatterSatStation, scatterSatEpidemio, scatter2Sat_Temporel, scatter2Sat_Spatial
from Util import *

import logging
logger = logging.getLogger(__name__)


tmpDir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'teledm/tmp')

def server_error(request):
    response = render('teledm/500.html',context_instance=RequestContext(request))
    response.status_code = 500
    return response

def proxyNCSS(request, path):
    params = '?' + '&'.join(['{}={}'.format(k,v) for k,v in request.GET.iteritems()])
    url = "https://climdata.u-bourgogne.fr/thredds/ncss/{}?{}".format(path,params)
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
    return HttpResponse(response.content)


def proxyDownload(request, path):
    params = '?' + '&'.join(['{}={}'.format(k,v) for k,v in request.GET.iteritems()])
    url = os.path.join(settings.TDS_URL % (settings.TDS_USER+':'+settings.TDS_PWD+'@'),path+params)
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
    return HttpResponse(response.content)


def proxyAjax(request, path):    
    url = os.path.join(settings.TDS_URL % (settings.TDS_USER +':'+settings.TDS_PWD+'@'), path)
    try:
        response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
    except requests.ConnectionError:
        print(url)
        return render('500.html', {'erreur':'Connexion Impossible'})
    return HttpResponse(response.content)
    

def colorbar(request, path):
    params = '?' + '&'.join(['{}={}'.format(k,v) for k,v in request.GET.iteritems()])
    url = os.path.join(settings.TDS_URL % (''), path+params)
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
    return HttpResponse(response.content, status=int(response.status_code))

def dates(request, path):
    params = '?' + '&'.join(['{}={}'.format(k,v) for k,v in request.GET.iteritems()])
    url = os.path.join(settings.TDS_URL % (''), path + params)
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
    return HttpResponse(response.content, status=int(response.status_code))


def minmax(request, path):
    params = '?' + '&'.join(['{}={}'.format(k,v) for k,v in request.GET.iteritems()])
    url = os.path.join(settings.TDS_URL % (''), path + params)
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
    return HttpResponse(response.content, status=int(response.status_code))


def proxyWMS(request, path):
    params = '?' + '&'.join(['{}={}'.format(k,v) for k,v in request.GET.iteritems()])
    url = os.path.join(settings.TDS_URL % (settings.TDS_USER+':'+settings.TDS_PWD+'@'),path+params)
    response = requests.get(url, auth=requests.auth.HTTPBasicAuth(settings.TDS_USER, settings.TDS_PWD), verify=False)
    return HttpResponse(response.content, status=int(response.status_code))


#@login_required
#@user_passes_test(lambda u: u.groups.filter(name='teledm').exists())
def home(request):
    return render(request, 'teledm/home.html')


#@login_required
#@user_passes_test(lambda u: u.groups.filter(name='teledm').exists())
def mapViewer(request):
    kwargs = request.POST
    print(kwargs)
    if request.is_ajax():
        variable = str(kwargs['variables'])
        logger.debug("Debug message!")
        logger.info("Info message!")
        logger.warning("Warning message!")
        logger.error("Error message!")
        logger.critical("Critical message!")
        if 'mesure' in kwargs.keys():
            fcsv = PathFile(**kwargs).csv
            df = pd.read_csv(fcsv, parse_dates={'datetime':['date']}, header=0, index_col=0, usecols=['date', variable])
            geo = kwargs['stations']
        else:
            fcsv = PathFile(**kwargs).csv
            try:
                geo = kwargs['district']
                csv = pd.read_csv(fcsv, parse_dates={'datetime':['date']}, header=0, index_col=0, usecols=['date', 'district', variable])
                df = csv[csv.district==geo]
            except KeyError:
                geo = kwargs['pays']
                df = pd.read_csv(fcsv, parse_dates={'datetime':['date']}, header=0, index_col=0, usecols=['date', variable])
        dictdatas = {'header':geo, 'varName':variable, 'datas':df[variable].replace(np.nan,'NaN').values.tolist(), 'dates':df.index.tolist()}        
        return HttpResponse(json.dumps(dictdatas, cls=DjangoJSONEncoder), content_type='text/json')
    else:
        logger.debug("Debug message!")
        logger.info("Info message!")
        logger.warning("Warning message!")
        logger.error("Error message!")
        logger.critical("Critical message!")
        return render(request, 'teledm/mapViewer.html')

#@login_required
#@user_passes_test(lambda u: u.groups.filter(name='teledm').exists())
def mapDist(request):
    kwargs = request.POST
    print kwargs
    if request.is_ajax():
        if 'capteur' in kwargs.keys():
            print 'capteur'
            ddirout = settings.MEDIA_ROOT
            deb = kwargs['datedebut']
            fin = kwargs['datefin']
            pays = kwargs['pays']
            niveau = kwargs['decoupage'] 
            types = kwargs['type'] 
            sat = kwargs['capteur']
            prod = kwargs['produit']
            res_temp = kwargs['pasdetemps']
            res = kwargs['resospatiale']
            varname = kwargs['variables']
            if 'level1' in kwargs.keys():
                level = int(kwargs['level1']) - 1
            else:
                level = -1
            ncfile = PathFile(**kwargs).nc
            fshape = PathFile(**kwargs).carto
            ldf, filename = calc_moy(ddirout,ncfile, fshape, deb,fin,pays,niveau,types,sat,prod,res_temp,res,varname,level)
            val = [traitementDF(x,y) for x,y in [(ldf,z) for z in ldf.keys() if z != 'nbpx']]
            datas = dict(zip([val[i][0] for i in range(4)],[val[i][1] for i in range(4)]))
            list_dates = ldf['vmean'].index.values.tolist()
            geojson = pays+"_"+niveau+"_sante.geojson"
            dictdatas = {'dates':list_dates,'datas':datas,'shape':geojson, 'filename':filename}
            print(filename)
        elif 'mesure' in kwargs.keys():
            variable = str(kwargs['variables'])
            fcsv = PathFile(**kwargs).csv
            df = pd.read_csv(fcsv, parse_dates={'datetime':['date']}, header=0, index_col=0, usecols=['date', variable])
            geo = kwargs['stations']
            dictdatas = {'header':geo, 'varName':variable, 'datas':df[variable].replace(np.nan,'NaN').values.tolist(), 'dates':df.index.tolist()}
        else:
            variable = str(kwargs['variables'])
            fcsv = PathFile(**kwargs).csv
            try:
                geo = kwargs['district']
                csv = pd.read_csv(fcsv, parse_dates={'datetime':['date']}, header=0, index_col=0, usecols=['date', 'district', variable])
                df = csv[csv.district==geo]
            except KeyError:
                geo = kwargs['pays']
                df = pd.read_csv(fcsv, parse_dates={'datetime':['date']}, header=0, index_col=0, usecols=['date', variable])
            dictdatas = {'header':geo, 'varName':variable, 'datas':df[variable].replace(np.nan,'NaN').values.tolist(), 'dates':df.index.tolist()}
        return HttpResponse(json.dumps(dictdatas, cls=DjangoJSONEncoder), content_type='application/json')
    else:
        if 'submit' in kwargs.keys():
            print(os.path.join(tmpDir, kwargs['filename']))
            filesend = os.path.join(tmpDir, kwargs['filename'])
            return sendfile(request, filesend)
        else:
            return render(request, 'teledm/mapDist.html')

#@login_required
#@user_passes_test(lambda u: u.groups.filter(name='teledm').exists())
def calval(request):
    if request.is_ajax():
        POST = request.POST.copy()
        try:
            ulx = float(POST['ulx'])
            uly = float(POST['uly'])
            lrx = float(POST['lrx'])
            lry = float(POST['lry'])
        except:
            ulx = POST['ulx']
            uly = POST['uly']
            lrx = POST['lrx']
            lry = POST['lry']
        z_buffer = POST.get('buffer', '')
        try:
            z_buffer = int(z_buffer)
        except:
            pass
        pas_de_temps1 = POST['pasdetemps1']
        datedebut = POST['datedebut']
        datefin = POST['datefin']
        type1 = POST['type1']
        sat1 = POST['capteur1']
        prd_sat1 = POST['produit1']
        res_sat1 = POST['resospatiale1'][3:]
        variable_sat1 = POST['variable1']
        if 'level1' in POST.keys():
            level_sat1 = int(POST['level1']) - 1
        else:
            level_sat1 = -1
        ncfile1 = PathFile(**POST).nc1
        if 'type2' in POST.keys():
            ncfile2 = PathFile(**POST).nc2
            type2 = POST['type2']
            sat2 = POST['capteur2']
            prd_sat2 = POST['produit2']
            res_sat2 = POST['resospatiale2'][3:]
            variable_sat2 = POST['variable2']
            if 'level2' in POST.keys():

templates/teledm/base.html
{% load staticfiles %}
<html lang=fr>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'select2/dist/css/select2.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'teledm/css/base.css' %}"/>
        {% block css %}{% endblock %}
        
        <!--
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
              <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
              <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        -->

        
        <title>TELEDM/TELEPAF</title>
    </head>
    <body>
        <nav id="navbar" class="navbar navbar-fixed-top navbar-light bg-faded" role="navigation">
            <div class="container-fluid">
                <div class="navbar-inner">
                    <ul class="nav navbar-nav" id="left">
                        <li class="active"><a href={% url 'teledm:home' %}><b>Accueil</b></a></li>
                        <li><a href={% url 'teledm:mapViewer' %}><b>Cartographie</b></a></li>
                        <li><a href={% url 'teledm:mapDist' %}><b>Extraction Géographique</b></a></li>
                        <li><a href={% url 'teledm:calval' %}><b>Calibration/Validation</b></a></li>
                        <li><a href={% url 'teledm:test' %}><b>test</b></a></li>
                    </ul>
                    <ul class="nav navbar-nav" id="right">
                        <!--<li class="nav-item"><a class="nav-link" href="/accounts/logout/"><b>Login/Logout</b></a></li>-->
                        <li class="nav-item"><a class="nav-link" href={% url 'portailCRC:home' %}><b>CRC</b></a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div data-spy="scroll" data-target="#navbar"   data-offset="0" class="Demo">
        <div class="container-fluid">
            <header class="row">
                <div class="col-lg-2" id="themes">
                    </br>
                    </br>
                    <h4><b>Teledetection</b></h4>
                    <h4><b>Poussieres</b></h4>
                    <h4><b>Meningite</b></h4>
                    <h4><b>IRA</b></h4>
                </div>
                <div class="col-lg-8">
                    <img src="{% static 'teledm/images/image_en_tete.jpeg' %}"/>
                </div>
                <div class="col-lg-2" id="missions">
                    </br>
                    </br>
                    <h2><b>TeleDM</b></h2>
                    <h2><b>TelePaF</b></h2>
                </div>
            </header>
            <div class="row">
                <aside_left class="col-lg-4" id="sectionForm">
                    {% block form %}{% endblock %}
                </aside_left>
                <section class="col-lg-8" id="section1">
                    {% block content1 %}{% endblock %}
                </section>
            </div>
            <div class="row">
                <section class="col-lg-12" id="section2">
                    {% block content2 %}{% endblock %}
                </section>
            </div>
            <footer>
                <div class="row" id="logos">
                    <img src="{% static 'teledm/images/cnrm.jpeg' %}"/>
                    <img src="{% static 'teledm/images/cnrs.jpeg' %}"/>
                    <img src="{% static 'teledm/images/crc.jpeg' %}"/>
                    <img src="{% static 'teledm/images/ehesp.jpeg' %}"/>
                    <img src="{% static 'teledm/images/institutPasteur.jpeg' %}"/>
                    <img src="{% static 'teledm/images/ird.jpeg' %}"/>
                    <img src="{% static 'teledm/images/ub.jpeg' %}"/>
                    <img src="{% static 'teledm/images/ulg.jpeg' %}"/>
                    <img src="{% static 'teledm/images/uLille1.jpeg' %}"/>                        
                </div>
           </footer>
        </div>
        <script type="text/javascript" src="{% static 'jquery/dist/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'jquery-ui/jquery-ui.js' %}"></script>
        <!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>-->
        <!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>-->
        <!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.js"></script>-->
        <!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.0/moment.min.js"></script>-->
        <!--<script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
        <script type="text/javascript" src="{% static 'jquery.cookie/jquery.cookie.js' %}"></script>
        <script type="text/javascript" src="{% static 'select2/dist/js/select2.js' %}"></script>
        <script type="text/javascript" src="{% static 'moment/min/moment.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'teledm/js/base.js' %}"></script>
        {% block js %}{% endblock %}
    </body>
</html>

templates/teledm/db.html
{% load staticfiles %}

<img src="{% static 'teledm/images/base1.png' %}"/>
<br><img src="{% static 'teledm/images/base2.png' %}"/>
<br><img src="{% static 'teledm/images/base3.png' %}"/>
<br><img src="{% static 'teledm/images/base4.png' %}"/>
<br><img src="{% static 'teledm/images/base5.png' %}"/>
<br><img src="{% static 'teledm/images/base6.png' %}"/>
<br><img src="{% static 'teledm/images/base7.png' %}"/>
<br><img src="{% static 'teledm/images/base8.png' %}"/>
<br><img src="{% static 'teledm/images/base9.png' %}"/>
<br><img src="{% static 'teledm/images/base10.png' %}"/>
<br><img src="{% static 'teledm/images/base11.png' %}"/>

templates/teledm/home.html
{% extends "teledm/base.html" %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'teledm/css/form.css' %}"/>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.20.0/ol.css"/>
    <link rel="stylesheet" href="https://openlayers.org/en/v3.20.0/css/ol.css" type="text/css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqtree/1.3.6/jqtree.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.3/themes/default/style.min.css"/>
    <style>
        .map {
            height: 400px;
            width: 100%;
        }
    </style>
{% endblock %}
{% block form %}
    </br>
    </br>
    </br>
    <div id="t">
       <h2>Accueil TeleDM</h2>
       
    </div>
    </br>
     <div>
        Structure et contenu de la base de données: <A HREF="{% url 'teledm:DB' %}" onClick="return popup(this, 'notes')">db </A><A HREF="{% url 'teledm:traitementsData' %}" onClick="return popup(this, 'notes')"> traitements Data</A>
    </div>
    </br>
    <div>
        <h3>Outil Cartographie</h3>
        Outil de visualisation de données issues de capteurs satellitaires, de modèles, de ré-analyses
        <A HREF="{% url 'teledm:tutoMap' %}" onClick="return popup(this, 'notes')">tuto cartographie</A>
    </div>
    </br>
    <div>
        <h3>Outil Extraction géographique</h3>
        Outil d'extraction de données issues de capteurs satellitaires, de modèles, de ré-analyses en s'appuyant
         sur différents découpages géographiques: aire de santé, district sanitaire, pays
         <A HREF="{% url 'teledm:tutoExtraction' %}" onClick="return popup(this, 'notes')">tuto Extraction</A>
    </div>
    </br>
    <div>
        <h3>Outil CalVal</h3>
        Outil premettant la confrontation de données satellitaires, modèles, ou ré-analyses entre elles ou avec des mesures in situ
        <A HREF="{% url 'teledm:tutoCalVal' %}" onClick="return popup(this, 'notes')">tuto CalVal</A>
    </div>
{% endblock form %}

{% block content1 %}
{% endblock %}

{% block content2 %}
{% endblock %}

{% block js %}
    
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqtree/1.3.6/tree.jquery.min.js"></script>
    <script type="text/javascript" src="https://code.highcharts.com/highcharts.js"></script>
    <!--<script type="text/javascript" src="https://code.highcharts.com/stock/highstock.js"></script>-->
    <!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqtree/1.3.6/tree.jquery.js"></script>-->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.3/jstree.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.20.0/ol.js"></script>
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="{% static 'teledm/js/home.js' %}"></script>
{% endblock %}

    

templates/teledm/localisation.html
{% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'teledm/css/form.css' %}"/>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.20.0/ol.css"/>
    <link rel="stylesheet" href="https://openlayers.org/en/v3.20.0/css/ol.css" type="text/css">


<div id="map"></div>
<script>
    map = new OpenLayers.Map("map");
    map.addLayer(new OpenLayers.Layer.OSM());
    map.zoomToMaxExtent();
</script>

<script type="text/javascript" src="http://openlayers.org/api/OpenLayers.js"></script>
<script type="text/javascript" src="{% static 'teledm/js/localisation.js' %}"></script>  

templates/teledm/stations.html
{% load staticfiles %}

<img src="{% static 'teledm/images/stations.png' %}"/>
<img src="{% static 'teledm/images/listeStations.png' %}"/>

templates/teledm/test.html
{% extends "teledm/base.html" %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="http://openlayers.org/en/v3.18.2/css/ol.css" type="text/css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'teledm/css/form.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'teledm/css/mapViewer.css' %}"/>
{% endblock %}

{% block form %}
    {% csrf_token %} 
    <div id="panel" type="button" id="update" class="btn btn-primary" onclick="majLayer()">Update Map</div>
    <div id="panel" type="button" id="download" class="btn btn-primary" onclick="download()">Download</div>
    <div id="panel" type="button" id="readCat" class="btn btn-primary" onclick="readCat()">readCat</div>
    <div><input type="text" class="input-small" name="lrx" id="cat" placeholder="East"/></div>
{% endblock %}

{% block content1 %}
    </br>
    <div id="map" class="map" ></div>
{% endblock %}

{% block content2 %}
    
{% endblock %}

{% block js %}
    <script>
        var urlShp = "{% static 'teledm/shapes/' %}";
    </script>
    <!--<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>-->
    <script type="text/javascript" src="https://code.highcharts.com/highcharts.js"></script>
    <!--<script type="text/javascript" src="https://code.highcharts.com/stock/highstock.js"></script>-->
    <script type="text/javascript" src="http://openlayers.org/api/OpenLayers.js"></script>
    <script type="text/javascript" src="http://maps.stamen.com/js/tile.stamen.js?v1.3.2"></script>
    <script type="text/javascript" src="https://code.highcharts.com/modules/exporting.js"></script>
    <!--<script type="text/javascript" src="http://highcharts.github.io/export-csv/export-csv.js"></script>-->
    <script type="text/javascript" src="{% static 'highcharts-export-csv/export-csv.js' %}"></script>   
    <!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.js"></script>-->
    <!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.js"></script>-->
    <!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"></script>-->
    <script type="text/javascript" src="http://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
    <script type="text/javascript" src="{% static 'respond/src/respond.js' %}"></script>
    <script type="text/javascript" src="{% static 'html5shiv/dist/html5shiv-printshiv.js' %}"></script>
    <script type="text/javascript" src="{% static 'teledm/js/test.js' %}"></script>   
{% endblock %}

templates/teledm/traitementsData.html
organigramme de traitement des donnees

templates/teledm/tutoCalVal.html
{% load staticfiles %}

<img src="{% static 'teledm/images/calval.png' %}"/>

templates/teledm/tutoExtraction.html
{% load staticfiles %}

<img src="{% static 'teledm/images/extraction.png' %}"/>

templates/teledm/tutoMap.html
{% load staticfiles %}

<img src="{% static 'teledm/images/carto2.png' %}"/>